<?php
//project start
acf_add_local_field_group(array(
    'key' => 'group_5f0a920bd543d',
    'title' => 'Portfolio Option',
    'fields' => array(
        array(
            'key' => 'field_5f0a93936a3ae',
            'label' => 'Portfolio Grid',
            'name' => 'image_width',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                2 =>  '2 column',
                3 =>  '3 column',
                4 =>  '4 column',
                5 =>  '5 column',
                6 =>  '6 column',
                7 =>  '7 column',
                8 =>  '8 column',
                9 =>  '9 column',
                10 => '10 column',
                12 => 'Fulwidth',
            ),
            'default_value' => 3,
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'return_format' => 'value',
            'ajax' => 0,
            'placeholder' => '',
        ),
        array(
            'key' => 'field_5f0b0fc730f1b',
            'label' => 'Image Height',
            'name' => 'image_height',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'normal' => 'Normal',
                'big' => 'Big',
            ),
            'default_value' => 'normal',
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'return_format' => 'value',
            'ajax' => 0,
            'placeholder' => '',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'project',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'side',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));